/**
 * Smaller copies of an uploaded image, made on demand.
 *
 * Every upload was stored once, up to 2000px wide, and served at that size
 * to a phone as readily as to a desktop. Both renderers now offer a `srcset`
 * whose candidate URLs are derived by convention (`?w=480` on an upload,
 * `<id>-w480.webp` on a published site), and this is what makes those URLs
 * real: the first request for a width generates it and stores it beside the
 * original, so there is no database column to migrate and images uploaded
 * long before this — or generated by the AI — get variants too.
 *
 * Generation is deduplicated in-process: ten browsers asking for the same
 * width at once resize the file once.
 */

import sharp from "sharp";
import { ObjectStorageService, objectStorageClient, ObjectNotFoundError } from "./replit_integrations/object_storage/objectStorage";

/** The widths the renderers offer. Kept in step with shared/rendering/imageRender.ts. */
export const VARIANT_WIDTHS = [480, 960, 1600];

/** Only uploads have variants; the path shape is part of the contract with the renderers. */
const UPLOAD_PATH_RE = /^\/objects\/uploads\/([A-Za-z0-9-]+)\.webp$/;

export function isVariantWidth(width: unknown): width is number {
  return typeof width === "number" && VARIANT_WIDTHS.indexOf(width) !== -1;
}

/**
 * The requested width for an upload, or null when this request is not one.
 * Anything outside the fixed set is refused rather than resized: a `?w=`
 * that anyone can pick is a way to fill a bucket.
 */
export function parseVariantRequest(objectPath: string, rawWidth: unknown): number | null {
  if (!UPLOAD_PATH_RE.test(objectPath)) return null;
  const width = typeof rawWidth === "string" ? Number(rawWidth) : typeof rawWidth === "number" ? rawWidth : NaN;
  return isVariantWidth(width) ? width : null;
}

/** Where the variant lives: beside the original, under the same id. */
export function variantObjectPath(objectPath: string, width: number): string | null {
  const match = UPLOAD_PATH_RE.exec(objectPath);
  if (!match || !isVariantWidth(width)) return null;
  return `/objects/uploads/${match[1]}-w${width}.webp`;
}

const inFlight = new Map<string, Promise<string | null>>();

async function generate(service: ObjectStorageService, objectPath: string, width: number, variantPath: string): Promise<string | null> {
  // Already made by an earlier request (or an earlier process).
  try {
    await service.getObjectEntityFile(variantPath);
    return variantPath;
  } catch (error) {
    if (!(error instanceof ObjectNotFoundError)) throw error;
  }

  const original = await service.getObjectEntityFile(objectPath);
  const [buffer] = await original.download();
  const resized = await sharp(buffer)
    .resize(width, null, { withoutEnlargement: true, fit: "inside" })
    .webp({ quality: 78 })
    .toBuffer();

  const privateObjectDir = service.getPrivateObjectDir();
  const fullPath = `${privateObjectDir}${privateObjectDir.endsWith("/") ? "" : "/"}${variantPath.replace("/objects/", "")}`;
  const parts = fullPath.startsWith("/") ? fullPath.slice(1).split("/") : fullPath.split("/");
  const bucket = objectStorageClient.bucket(parts[0]);
  await bucket.file(parts.slice(1).join("/")).save(resized, { contentType: "image/webp", resumable: false });
  return variantPath;
}

/**
 * The stored path of this width's copy, generating it if needed. Null when
 * the width is not offered, the original is missing, or the resize failed —
 * callers then serve the original, which is always correct, only larger.
 */
export async function getOrCreateImageVariant(objectPath: string, width: number): Promise<string | null> {
  const variantPath = variantObjectPath(objectPath, width);
  if (!variantPath) return null;

  const pending = inFlight.get(variantPath);
  if (pending) return pending;

  const service = new ObjectStorageService();
  const work = generate(service, objectPath, width, variantPath)
    .catch((error) => {
      // A missing original is ordinary (an external URL, a deleted file);
      // anything else is worth seeing in the log. Either way the caller
      // serves the original.
      if (!(error instanceof ObjectNotFoundError)) {
        console.error(`[images] variant ${variantPath} failed:`, error);
      }
      return null;
    })
    .finally(() => {
      inFlight.delete(variantPath);
    });

  inFlight.set(variantPath, work);
  return work;
}

/**
 * Make every variant for a freshly uploaded image, in the background.
 *
 * The first visitor to a new page would otherwise pay the resize; warming
 * moves that cost to the upload, where someone is already waiting.
 */
export async function warmVariants(objectPath: string): Promise<void> {
  if (!UPLOAD_PATH_RE.test(objectPath)) return;
  await Promise.all(VARIANT_WIDTHS.map((width) => getOrCreateImageVariant(objectPath, width)));
}
