/**
 * Media storage paths arrive from the client (POST /api/websites/:id/media)
 * but are later handed to the Supabase SERVICE-ROLE client for deletion,
 * which bypasses RLS. Without validation one tenant could register an asset
 * row pointing at another tenant's object and then destroy it.
 *
 * Only two shapes are legitimate:
 *   1. "<websiteId>/<filename>"       - Supabase media bucket, site-scoped.
 *      Generated by POST /api/websites/:id/media/upload-url.
 *   2. "/objects/<segment>/<file>"    - Replit object storage, per-object uuid
 *      namespace. Generated by POST /api/uploads/optimized-image, which
 *      returns e.g. "/objects/uploads/<uuid>.webp".
 */

const MAX_STORAGE_PATH_LENGTH = 512;
const OBJECT_STORAGE_RE = /^\/objects\/[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/;

export function isAllowedMediaStoragePath(
  storagePath: unknown,
  websiteId: string
): boolean {
  if (typeof storagePath !== "string") return false;
  if (storagePath.length === 0 || storagePath.length > MAX_STORAGE_PATH_LENGTH) {
    return false;
  }
  // Reject traversal and separator tricks before any prefix matching.
  if (
    storagePath.includes("..") ||
    storagePath.includes("\\") ||
    storagePath.includes("\0")
  ) {
    return false;
  }

  if (OBJECT_STORAGE_RE.test(storagePath)) return true;

  if (!websiteId) return false;
  const prefix = `${websiteId}/`;
  if (!storagePath.startsWith(prefix)) return false;

  const remainder = storagePath.slice(prefix.length);
  return remainder.length > 0 && !remainder.includes("/");
}
