/**
 * Media storage paths arrive from the client (POST /api/websites/:id/media)
 * but are later handed to the Supabase SERVICE-ROLE client for deletion,
 * which bypasses RLS. Without validation one tenant could register an asset
 * row pointing at another tenant's object and then destroy it.
 *
 * Only two shapes are legitimate:
 *   1. "<websiteId>/<filename>"       - Supabase media bucket, site-scoped.
 *      Generated by POST /api/websites/:id/media/upload-url.
 *   2. "/objects/<segment>/<file>"    - Replit object storage, per-object uuid
 *      namespace. Generated by POST /api/uploads/optimized-image, which
 *      returns e.g. "/objects/uploads/<uuid>.webp".
 */

const MAX_STORAGE_PATH_LENGTH = 512;
const OBJECT_STORAGE_RE = /^\/objects\/[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/;

export function isAllowedMediaStoragePath(
  storagePath: unknown,
  websiteId: string
): boolean {
  if (typeof storagePath !== "string") return false;
  if (storagePath.length === 0 || storagePath.length > MAX_STORAGE_PATH_LENGTH) {
    return false;
  }
  // Reject traversal and separator tricks before any prefix matching.
  if (
    storagePath.includes("..") ||
    storagePath.includes("\\") ||
    storagePath.includes("\0")
  ) {
    return false;
  }

  if (OBJECT_STORAGE_RE.test(storagePath)) return true;

  if (!websiteId) return false;
  const prefix = `${websiteId}/`;
  if (!storagePath.startsWith(prefix)) return false;

  const remainder = storagePath.slice(prefix.length);
  return remainder.length > 0 && !remainder.includes("/");
}

/**
 * What a PATCH of a media asset may change.
 *
 * The route used to pass `req.body` straight to the update, so any column —
 * `storagePath` above all, which the delete route hands to the service-role
 * client — could be rewritten by anyone who can edit media. Two fields
 * describe how an image is *used* and are the only ones the editor sets;
 * everything else describes the stored file and is written on upload.
 */
export function parseMediaAssetPatch(
  body: unknown
): { value: { altText?: string; crop?: { x: number; y: number; width: number; height: number } | null } } | { error: string } {
  if (!body || typeof body !== "object" || Array.isArray(body)) return { error: "Ugyldigt indhold" };
  const input = body as Record<string, unknown>;
  const value: { altText?: string; crop?: { x: number; y: number; width: number; height: number } | null } = {};

  if ("altText" in input) {
    const altText = input.altText;
    if (altText !== null && typeof altText !== "string") return { error: "altText skal være tekst" };
    value.altText = typeof altText === "string" ? altText.slice(0, 250) : "";
  }

  if ("crop" in input) {
    const crop = input.crop;
    if (crop === null) {
      value.crop = null;
    } else {
      if (!crop || typeof crop !== "object" || Array.isArray(crop)) return { error: "crop er ugyldig" };
      const c = crop as Record<string, unknown>;
      const numbers = ["x", "y", "width", "height"].map((key) => c[key]);
      if (numbers.some((n) => typeof n !== "number" || !isFinite(n as number))) return { error: "crop er ugyldig" };
      const [x, y, width, height] = numbers as number[];
      if (width <= 0 || height <= 0 || x < 0 || y < 0) return { error: "crop er ugyldig" };
      value.crop = { x, y, width, height };
    }
  }

  if (Object.keys(value).length === 0) return { error: "Intet at opdatere" };
  return { value };
}
