/**
 * In-memory design-proposal store — Task #169
 *
 * Design proposals are generated by the `propose_design_directions` tool and
 * live in this store until the user explicitly approves or rejects them.
 * They are deliberately in-memory (not DB-persisted) because:
 *   1. Proposals are session-scoped — they are almost always resolved within
 *      the same conversation that produced them.
 *   2. A server restart simply means the user generates fresh directions; no
 *      data loss that would affect the live site (proposals are never applied
 *      to the live builder state until approved).
 *
 * The critical guarantee: NOTHING in this store touches `builder_state` or
 * its revision until `approveProposal` is called and the returned mutations
 * are applied through the normal CAS path.
 */

import { randomUUID } from "crypto";
import type { BuilderMutation } from "@shared/aiBuilderSchema";
import type { DesignDirection, BrandDeviation, DesignIntent } from "@shared/creativeTypes";

export type DesignProposal = {
  id: string;
  websiteId: string;
  direction: DesignDirection;
  /**
   * The mutations that would move the site from `baseRevision` to the
   * proposed state. Stored here, not applied, until explicit approval.
   * For in-session applications (apply_design_direction + write tools),
   * this is populated post-run for informational purposes.
   */
  mutations: BuilderMutation[];
  /**
   * The builder_state revision this proposal was generated against.
   * Approval is rejected if the live revision has advanced past this
   * (same principle as the plan CAS check — the site the user approved
   * must match the site the mutations target).
   */
  baseRevision: number;
  /**
   * pending  → direction cards shown, not yet applied
   * applied  → agent already applied the changes in-session; replay is blocked
   * approved → direction applied via the approve API (card-only flow)
   * rejected → dismissed without applying
   */
  status: "pending" | "applied" | "approved" | "rejected";
  /**
   * True for high-deviation (experimental) directions that are in "applied"
   * status but whose post-application evolution choice (keep here / apply
   * site-wide / add to brand guide) has not yet been completed.
   * Cleared by the add-to-brand-guide and apply-site-wide endpoints so the
   * panel can stop showing the offer card after a choice is made.
   * The GET /ai/proposals endpoint surfaces these so the card can be
   * restored after a page refresh.
   */
  pendingEvolutionChoice?: boolean;
  createdAt: Date;
  resolvedAt?: Date;
};

/** Max proposals kept per website at once. Oldest are evicted first. */
const MAX_PROPOSALS_PER_SITE = 10;

const store = new Map<string, DesignProposal>();

/** Stable short id for a new proposal. */
function makeProposalId(): string {
  return "dir-" + randomUUID().slice(0, 8);
}

/**
 * Store a new design proposal and return it.
 * Does NOT touch builder_state.
 */
export function storeProposal(args: {
  websiteId: string;
  direction: Omit<DesignDirection, "id">;
  mutations: BuilderMutation[];
  baseRevision: number;
}): DesignProposal {
  const id = makeProposalId();
  const proposal: DesignProposal = {
    id,
    websiteId: args.websiteId,
    direction: { ...args.direction, id },
    mutations: args.mutations,
    baseRevision: args.baseRevision,
    status: "pending",
    createdAt: new Date(),
  };

  // Evict oldest pending proposals for this website if over the cap
  const siteProposals = getAllForWebsite(args.websiteId, "pending");
  if (siteProposals.length >= MAX_PROPOSALS_PER_SITE) {
    const oldest = siteProposals
      .sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime())
      .slice(0, siteProposals.length - MAX_PROPOSALS_PER_SITE + 1);
    for (const p of oldest) store.delete(p.id);
  }

  store.set(id, proposal);
  return proposal;
}

/** Get a proposal by id, regardless of status. */
export function getProposal(id: string): DesignProposal | undefined {
  return store.get(id);
}

/** All proposals for a website, optionally filtered by status. */
function getAllForWebsite(websiteId: string, status?: DesignProposal["status"]): DesignProposal[] {
  const out: DesignProposal[] = [];
  for (const p of Array.from(store.values())) {
    if (p.websiteId !== websiteId) continue;
    if (status !== undefined && p.status !== status) continue;
    out.push(p);
  }
  return out;
}

/** All pending proposals for a website, newest first. */
export function getPendingProposals(websiteId: string): DesignProposal[] {
  return getAllForWebsite(websiteId, "pending").sort(
    (a, b) => b.createdAt.getTime() - a.createdAt.getTime()
  );
}

/**
 * Mark a proposal as approved and return it with its mutations.
 * The caller is responsible for applying those mutations through the
 * normal CAS path (applyMutation → save → bump revision).
 *
 * Returns undefined if the proposal does not exist or is no longer pending.
 */
export function approveProposal(id: string): DesignProposal | undefined {
  const p = store.get(id);
  if (!p || p.status !== "pending") return undefined;
  const approved = { ...p, status: "approved" as const, resolvedAt: new Date() };
  store.set(id, approved);
  return approved;
}

/**
 * Mark a proposal as rejected. The live site is untouched.
 * Returns undefined if the proposal does not exist or is no longer pending.
 */
export function rejectProposal(id: string): DesignProposal | undefined {
  const p = store.get(id);
  if (!p || p.status !== "pending") return undefined;
  const rejected = { ...p, status: "rejected" as const, resolvedAt: new Date() };
  store.set(id, rejected);
  return rejected;
}

/**
 * Replace the mutations stored on a pending proposal.
 * Called by `apply_design_direction` once it has computed the concrete
 * mutation list for the chosen direction.
 * Works on pending proposals only; applied/approved/rejected are immutable.
 */
export function updateProposalMutations(id: string, mutations: BuilderMutation[]): void {
  const p = store.get(id);
  if (p && p.status === "pending") {
    store.set(id, { ...p, mutations });
  }
}

/**
 * Mark a proposal as applied — its changes were committed to the live site
 * by the agent in this session. This prevents the approve API from replaying
 * the mutations and duplicating already-applied changes.
 *
 * For high-deviation (experimental) directions, sets pendingEvolutionChoice=true
 * so the panel can restore the post-apply evolution offer card after a reload.
 * Cleared by the add-to-brand-guide and apply-site-wide endpoints.
 *
 * Returns undefined if the proposal does not exist or is no longer pending.
 */
export function markProposalApplied(id: string): DesignProposal | undefined {
  const p = store.get(id);
  if (!p || p.status !== "pending") return undefined;
  const isExperimental = p.direction.brandDeviation?.level === "high";
  const applied: DesignProposal = {
    ...p,
    status: "applied" as const,
    resolvedAt: new Date(),
    pendingEvolutionChoice: isExperimental ? true : undefined,
  };
  store.set(id, applied);
  return applied;
}

/**
 * Clear the pending evolution choice flag after the user makes an explicit
 * post-application choice (add-to-brand-guide or apply-site-wide or dismiss).
 * No-op for proposals that don't have the flag or don't exist.
 */
export function clearEvolutionChoice(id: string): void {
  const p = store.get(id);
  if (p && p.pendingEvolutionChoice) {
    store.set(id, { ...p, pendingEvolutionChoice: undefined });
  }
}

/**
 * All applied proposals for a website that still have an unresolved
 * evolution choice (high-deviation directions waiting for user input).
 * Used by the GET /ai/proposals endpoint to restore offer cards on reload.
 */
export function getPendingEvolutionOffers(websiteId: string): DesignProposal[] {
  const out: DesignProposal[] = [];
  for (const p of Array.from(store.values())) {
    if (p.websiteId === websiteId && p.status === "applied" && p.pendingEvolutionChoice) {
      out.push(p);
    }
  }
  return out.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
}

/**
 * Supersede all pending proposals for a website (called when the user
 * makes a direct edit that makes prior proposals obsolete).
 */
export function supersedePendingProposals(websiteId: string): void {
  for (const [id, p] of Array.from(store.entries())) {
    if (p.websiteId === websiteId && p.status === "pending") {
      store.set(id, { ...p, status: "rejected", resolvedAt: new Date() });
    }
  }
}

// ── helpers exposed for tests ──────────────────────────────────────────────

/** Clear all proposals (test helper only). */
export function _clearAllProposals(): void {
  store.clear();
}

/** Total proposal count (test helper). */
export function _proposalCount(): number {
  return store.size;
}

/**
 * Derive the BrandDeviation level from the count and importance of changes.
 *
 * Rules (pure function — easily unit tested):
 *   0 changes → "none"
 *   1 change  → "low"
 *   2–3       → "medium"
 *   ≥4        → "high"
 *
 * Overrides: if any change mentions "palette" or "skrifttype" (font), the
 * level is bumped at least one notch above the count-based level, because
 * those affect the entire site at once.
 */
export function deriveBrandDeviationLevel(changes: string[]): import("@shared/creativeTypes").BrandDeviationLevel {
  if (changes.length === 0) return "none";
  const baseLevel = changes.length === 1 ? "low" : changes.length <= 3 ? "medium" : "high";
  const hasBigChange = changes.some(
    (c) =>
      /palette|skrifttype|fontfamilie|typografi|layout/i.test(c)
  );
  if (!hasBigChange) return baseLevel;
  // Bump one notch
  const order = ["none", "low", "medium", "high"] as const;
  const idx = order.indexOf(baseLevel);
  return order[Math.min(idx + 1, order.length - 1)];
}

/**
 * Classify the design intent from the deviation level.
 * Matches the DesignIntent union.
 */
export function classifyDesignIntent(level: import("@shared/creativeTypes").BrandDeviationLevel): DesignIntent {
  if (level === "none" || level === "low") return "brand_aligned";
  if (level === "medium") return "brand_evolution";
  return "experimental";
}
